export const NEW_GAME = 'NEW_GAME_BOARD_TRAY';
export const ADD_NEW_WORD = 'ADD_NEW_WORD';
export const UPDATE_HORIZONTAL_SIZE = 'UPDATE_HORIZONTAL_SIZE';
export const UPDATE_VERTICAL_SIZE = 'UPDATE_VERTICAL_SIZE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const COUNT_DOWN = 'COUNT_DOWN_TIMER';